### ISSUE TITLE
Folders API : creation

### ISSUE THREAD

**Issue by deelanM** [Badsender-com/LePatron.email#147]
## Description

Parent issue : #29 
Endpoint for folder creation 

```
POST /folders
Body {
 name : String (required),
 workspaceId : String (required),
 parentFolderId : String
}
```

## Tasks

- [x] `folder.routes` : add creation route
- [x] `folder.controller` : add `create` function. Checks if user is member of provided workspace.
- [x] `folder.service` : add creation function.
