### ISSUE TITLE
Check box not showing when we delete workspace that contain mails or folders

### ISSUE THREAD

**Issue by medamineziraoui** [Badsender-com/LePatron.email#176]
### Expected behavior:

When we intend to delete a workspace that doesn't contain mail or folder. we get a modal that expect us to confirm the deletion by providing the name of the workspace, but if the workspace contain folders or mails then the delete modal have to show a checkbox + providing the input of the workspace to confirm the deletion.

### Current Behavior:
Workspace that contain mail or folder does not show a checkbox confirmation when we try the workspace in question.

### Tasks:
- [ ] Confirm in front part if we get checkbox with folders and mails
- [ ] Populate mail and folder with a _workspace in mongo ( test each time the behavior with the modal )
- [ ] Check if the error is a front side or back side, if front side then fix it, if back then report the problem
