### ISSUE TITLE
API : endpoint for multiple mails shifting

### ISSUE THREAD

**Issue by deelanM** [Badsender-com/LePatron.email#186]
## Description

Parent issue : #45 
Endpoint for moving multiple mailings to a workspace

## Tasks

- [x] `mailing.routes` : add POST route `/move-many`
```
POST /mailings/move-many

Body {
 mailingsIds : Array, // mailings Ids to move
 workspaceId : String // destination workspace's id
}
```

- [x] `mailings.controller` : add `moveMany` function. Checks if all mailings have same source
- [x] `mailings.service` : add `moveMany` function. Implements shifting logic similar to `move`
