### ISSUE TITLE
Folders API : deletion

### ISSUE THREAD

**Issue by deelanM** [Badsender-com/LePatron.email#243]
## Description

Parent issue : #29 
Endpoint for folder deletion

## Tasks 

- [x] `folder.routes` : add deletion endpoint 
```
DELETE /folders/:folderId
```
- [x] `folder.controller` : add deletion controller
- [x] `folder.service` : add deletion function, checks if user is member of folder's workspace, deletes folder and its content using recursive function `workspace.service.deleteFolderContent`
