### ISSUE TITLE
Tracking management in the template options

### ISSUE THREAD

**Issue by the2ne** [Badsender-com/LePatron.email#645]
## Context

As a user
I want to be able to define my tracking parameters in the template options
So that I don't have to change all the URLs manually

## TODO

- [ ] check the presence of URL parameters in the href when exporting the HTML
  - [ ] if existing tracking URL, then don't apply global template tracking 
  - [ ] if no tracking, then ad global template tracking
- [ ] add the tracking entered in the template options to the links that do not have tracking at the time of the HTML export

## UI

Ex : `https://www.test.test?utm_source=newsletter&utm_medium=email_newsletter&utm_campaign=campaign_name-en&utm_term=whatsnew`

- at least two text fields : 
  - _key_
  - _value_
- options:
  - UTM_SOURCE : to define
  - UTM_MEDIUM : preset with "EMAIL"
  - UTM_CAMPAIGN : preset with "EMAIL NAME"
  - 
![Screenshot 2022-11-29 at 15-42-09 Edit the one shot campaign test stage connecteur Actito](https://user-images.githubusercontent.com/5319082/204559357-f4541d78-eea2-4056-9eae-815e2eb722f1.png)
