### ISSUE TITLE
Quality control when exporting HTML: link

### ISSUE THREAD

**Issue by the2ne** [Badsender-com/LePatron.email#646]
## Context

As a user
I would like to be informed if a link has not been defined
In order not to send a campaign without a link

## Todo

- [ ] Check the href tags when exporting HTML
- [ ] if `#toreplace`, then alert message
- [ ] the alert message must specify
  - the name of the block
  - the name of the option 
  - the wording of the link
