### ISSUE TITLE
Quality control when exporting HTML: background image

### ISSUE THREAD

**Issue by the2ne** [Badsender-com/LePatron.email#647]
## Context

As a user
I would like to be informed if a background image is missing
In order to avoid errors when importing into my ESP

## Todo
when exporting HTML
- [ ] check the background-image URL properties
- [ ] if empty, then alert message
- [ ] the alert message must specify
  - the name of the block
  - the name of the option
  
When using the editor, if the user have had an image
- [ ] disable the upload button
- [ ] show the files name
- [ ] show the dimensions

### UI exemples

**Current**
![Image](https://user-images.githubusercontent.com/5319082/197530398-9e6dec22-34bf-4ef8-b248-bccfca780486.png)

**Upload button disabled**
![Image](https://user-images.githubusercontent.com/5319082/197530399-f50ba970-fee4-4132-bb6c-0619f240f831.png)

**Image informations**
![Image](https://user-images.githubusercontent.com/5319082/197530401-cc067da2-3a5b-4da6-8231-f6438b5dee83.png)

Reset disabled & Upload no button
![Image](https://user-images.githubusercontent.com/5319082/197530400-3fbe13e5-84cb-4e03-99ae-1c4412f61df9.png)
