### ISSUE TITLE
Personalization variables::Frontend

### ISSUE THREAD

**Issue by omar-bear** [Badsender-com/LePatron.email#708]
## Description
Display the management table of personalized variables in a group's settings. The functionalities include creating, updating, deleting, and listing the variables.

The idea is to create a "repeater" to add personalized variables and save them using a submit button.

Here's an example of a form: source: https://formiz-examples.netlify.app/repeater

<img width="695" alt="image" src="https://github.com/Badsender-com/LePatron.email/assets/80390318/b175dfed-ce0b-4aca-a34f-e0d41d3f7eda">

## Tasks

- [ ] Create a form component for adding personalized variables.
- [ ] Add fields for the label and the variable.
- [ ] Add an "Add" button to add the variable to the table.
- [ ] Add a "Save Changes" button to save all changes made to the table.
- [ ] Add "Edit" and "Delete" buttons to each row of the table to allow for editing or deleting specific variables.
- [ ] Connect the form to the backend via the appropriate API endpoints.

## Acceptance Criteria

- [ ] Users can add new personalized variables via the form.
- [ ] Users can edit and delete existing variables from the table.
- [ ] Changes made to variables are correctly saved and persistent.
- [ ] Validation errors are properly handled and displayed to the user.

## Time Estimation

2-3 days.
